### PR TITLE
Better trim generation

### PR DESCRIPTION
**Pull request by kikugie**
## This is still in development, PR is mainly for testing and discussion for now.

It makes trimmable items not depend on `Equipment`, but rather filters them ahead of time. This is done to allow any arbitrary item to have dynamic trims (such as tools, if you somehow fit the textures).  
Additionally, `GroupPermutationsAtlasSource` is now used for trim declaration. Instead of specifying every trim pattern, it takes a list of directories to collect textures from. This also prevents Minecraft from creating unused textures when Dynamic Trim is not installed.

### CODE REVIEW

**Comment by kikugie** [comment]
Also, there's an existing problem, both on this and 1.2.1 release:  
image

image


For some reason it doesn't work on anything but armour.

**Comment by kikugie** [comment]
I'm also thinking of a way to use json files in resourcepacks to specify trim sources. This way datapacks would be able to add compatibility. API has an advantage of providing dynamic list of items (e.g. "Dynamic Trinket Trims" mod would be possible)

**Comment by Bawnorton** [comment]
Thanks for re-organising this, I should have spent longer actually thinking it through rather than just splitting it up and throwing it all in the util package 💀. It felt wrong even when I was doing it.

**Comment by kikugie** [comment]
:oain: the custom trimmable items compat bug goes a bit deeper. So, first of all, an item must have overrides already specified, which is not ideal. Then if the specified overrides are from a different namespace, its not able to find them.  

I want to try removing dependency on initial item overrides, but I won't be able this weekend. If you want to try, use https://modrinth.com/datapack/trimmable-tools

**Comment by Bawnorton** [comment]
Yeah the goal was to change the textures of the existing trims, not adding new ones.

**Comment by Bawnorton** [comment]
@kikugie are you good for me to merge this?

**Comment by kikugie** [comment]
I completely forgot about this. Iirc stuff other than armor still wasn't quite working, but that can be solved separately

**Pull request merged**
